#!/bin/bash

mkdir -p ~/.ssh
[ -f ~/.ssh/environment ]      || touch -a ~/.ssh/environment
[ -f ~/.ssh/authorized_keys ]  || touch -a ~/.ssh/authorized_keys
[ -f ~/.ssh/environment_temp ] || touch -a ~/.ssh/environment_temp
chmod 755 ~ ~/.ssh ~/.ssh/authorized_keys
