#!/bin/bash

_LoadAgent()
{
   if [ "${SSH_AGENT_PID-x}" == "x" ]
   then
      ( [ -f ~/.ssh-agent-env ] && source ~/.ssh-agent-env >/dev/null && [ "$SSH_AGENT_PID" != "$(pgrep -f '^ss[h]-agent')" ] && rm -f ~/.ssh-agent-env )

      [ ! -f ~/.ssh-agent-env ] && ssh-agent -s > ~/.ssh-agent-env

      source ~/.ssh-agent-env
   fi
}

if [ "$PROMPT_COMMAND" ]
then
   PROMPT_COMMAND="_LoadAgent;$PROMPT_COMMAND"
else
   PROMPT_COMMAND="_LoadAgent"
fi
