#!/bin/bash

echo -n "Type password: "
read -s pass
echo

H=$(echo -n "$pass" | sha1sum | tr 'a-z' 'A-Z')
F=$(echo "$H" | sed -e 's/^\(.....\).*/\1/')
S=$(echo "$H" | sed -e 's/^.....\([^[:space:]]*\).*/\1/')

R=$(curl -s "https://api.pwnedpasswords.com/range/$F" | grep "$S")

if [ "$R" ]
then
   echo "PWNED - $(echo $R | sed -e 's/.*://')"
else
   echo "SAFE"
fi
