#!/bin/bash

enc()
{
   local ENCODING="$1"; shift;

   case "$ENCODING" in
      base64)
         cat "$@" | perl -MMIME::Base64 -n -e 'print encode_base64 $_'
         ;;
      quoted-printable|quotedprintable|qp)
         cat "$@" | perl -MMIME::QuotedPrint -n -e 'print encode_qp $_'
         ;;
      uri)
         cat "$@" | perl -MURI::Escape -n -e 'print uri_escape $_'
         ;;
      help|*)
         xhelp
         ;;
   esac
}


dec()
{
   local ENCODING="$1"; shift;

   case "$ENCODING" in
      base64)
         cat "$@" | perl -MMIME::Base64 -n -e 'print decode_base64 $_'
         ;;
      quoted-printable|quotedprintable|qp)
         cat "$@" | perl -MMIME::QuotedPrint -n -e 'print decode_qp $_'
         ;;
      uri)
         cat "$@" | perl -MURI::Escape -n -e 'print uri_unescape $_'
         ;;
      help|*)
         xhelp
         ;;
   esac
}


xhelp()
{
   echo "Usage: $(basename "$0") <enc|dec> <base64|quoted-printable|qp|uri> [<file>]" 1>&2
   exit 1
}


main()
{
   local ENC_DEC="$1"; shift;

   case "$ENC_DEC" in
      enc)
         enc "$@";
         ;;
      dec)
         dec "$@";
         ;;
      help|*)
         xhelp
         ;;
   esac
}


main "$@"
