#!/bin/bash

if [ $# -eq 0 ]
then
   echo "Usage: $0 <expression>"
   exit 1
fi

E="$1"; shift

docker images | awk '/'"$E"'/ {
                        if($2 == "<none>") {
                           print $3
                        }
                        else {
                           print $1 ":" $2
                        }
                     }'
