#!/bin/bash

if [ $# -eq 0 ]
then
   echo "Usage: $0 <expression>"
   exit 1
fi

E="$1"; shift

RM=0
if [ $# -gt 0 ]
then
   if [ "$1" == "--rm" ]
   then
      RM="1";
   fi
fi

docker images | awk '/'"$E"'/ {
                        if($2 == "<none>") {
                           print $3
                        }
                        else {
                           print $1 ":" $2
                        }
                     }' | (
                             if [ "$RM" == 1 ]
                             then
                                xargs docker rmi -f
                             else
                                cat
                             fi
                          )
