#!/bin/bash

COLS=$(tput cols)

FMT="tformat:"
FMT="${FMT} --. %C(auto)%h%d%n"
FMT="${FMT}   |- %s%n"
FMT="${FMT}   |- %Cgreen%cn%n"
FMT="${FMT}   |- %C(auto)%ar%n"
FMT="${FMT}   \`- %Cred%p%n"
FMT="${FMT}%n"

git log --format="$FMT" "$@"
