#!/bin/bash

#https://github.com/lee-dohm/dotfiles/blob/main/bin/git-oldest-ancestor

if [ $# -lt 1 ] || [ $# -gt 2 ]
then
    echo "Usage: git fp <rev1> [<rev2>]"
    exit 1
fi

set -euo pipefail

R1=""     && [ $# -ge 1 ] && R1=${1} && shift
R2="HEAD" && [ $# -ge 1 ] && R2=${1} && shift

R1=$(git rev-parse --short "${R1}")
R2=$(git rev-parse --short "${R2}")

fp=$(
    head -1 <(
        diff --old-line-format='' --new-line-format='' \
            <(git rev-list --first-parent "${R1}") \
            <(git rev-list --first-parent "${R2}")
    )
)

git rev-parse --short "$fp"
