#!/bin/bash
#
# Script for git ssh.
#
# Created By: gajanan.khandake@gmail.com
# Created On: May 28, 2015
#

/usr/bin/ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o CheckHostIP=no -o ServerAliveInterval=100 -q "$@"
