#!/bin/bash

TEMP="/tmp/_hindent.temp.$$"

trap "rm -f $TEMP.out $TEMP.err" EXIT QUIT KILL TERM

(
   cat "$@"  \
      | sed -e 's/[<]\/[A-Za-z]/\n&/' \
      | hindent -c -i3 -t0 -s \
      | sed -e '/^[ ]*$/d'

#      | awk '-F<' 'BEGIN {
#                      js = 0;
#                      command = "cat";
#                      PROCINFO[command, "pty"] = 1
#                   }
#                   
#                   /<\/script/ {
#                      close(command, "to");
#                      while ((command |& getline line) > 0)
#                        print line
#                      close(command)
#                      js = 0;
#                   }
#
#                   // {
#                      if(js == 1) {
#                         print |& command;
#                      }
#                      else {
#                         print;
#                      }
#                   }
#
#                   /<script/ {
#                      IND = $1;
#                      js = 1;
#                   }'


) 1> $TEMP.out 2> $TEMP.err

cat $TEMP.out

if [ -s $TEMP.err ]
then
   echo '<!--'
   cat $TEMP.err
   echo '-->'
fi
