#!/bin/bash

if [ "$(id -u)" != "0" ]
then
   sudo -E "$(\which "$0")" "$@"
   exit $?
fi

( /etc/init.d/ntp stop; until ping -nq -c3 8.8.8.8; do echo "Waiting for network..."; done; ntpdate -s time.nist.gov; /etc/init.d/ntp start )
