#!/bin/bash

EFILE=~/.errors.$$.cpp

trap "rm -f $EFILE" EXIT QUIT KILL TERM

OP=()

while [ $# -gt 0 ]
do
    case "$1" in
        --no-sp|--no-split)
            OP+=( '+set switchbuf-=split' )
            ;;
        --sp|--split)
            OP+=( '+set switchbuf+=split' )
            ;;
        -g)
            OP+=( '-g' )
            ;;
    esac
    shift
done

if which paint 1>/dev/null 2>/dev/null
then
   ( cat | tee "$EFILE" | paint )
else
   ( cat | tee "$EFILE" )
fi

# Regular expression to find pattern ':<digits>:'
if grep -q -e "\:[[:digit:]]\+\:" $EFILE
then
  [ $(cat "$EFILE" | sed -e "/^ *$/d" | wc -l) -gt 0 ] && ( exec </dev/tty ; ${EDITOR-vim} "${OP[@]}" +copen -q "$EFILE"; ) && exit 1
fi

exit 0
