#!/bin/bash

usage()
{
    echo "usage: qfix [-g] [<-s>|<--split>|<+s>|<--no-split>] [--help]"
}

ED_NAME="vim"
ED_OPTS=('-f')
ED_ARGS=('+copen')

while [ $# -gt 0 ]
do
    case "$1" in
        --help)
            usage
            exit 0
            ;;
        +s|--no-split)
            ED_ARGS+=( '+set switchbuf-=split' )
            ;;
        -s|--split)
            ED_ARGS+=( '+set switchbuf+=split' )
            ;;
        -g)
            ED_OPTS+=('-g')
            ;;
    esac
    shift
done

EFILE=$(mktemp /tmp/qfix.XXXXXX)

trap "rm -f '$EFILE'" EXIT QUIT KILL TERM

if which paint 1>/dev/null 2>/dev/null
then
   ( cat | tee "$EFILE" | paint )
else
   ( cat | tee "$EFILE" )
fi

# Regular expression to find pattern ':<digits>:'
if grep -q -e "\:[[:digit:]]\+\:" $EFILE
then
    if [ $(cat "$EFILE" | sed -e "/^ *$/d" | wc -l) -gt 0 ]
    then
        ( exec </dev/tty; "${ED_NAME}" "${ED_OPTS[@]}" -q "$EFILE" "${ED_ARGS[@]}")
        exit 1
    fi
fi

exit 0
