#!/bin/bash

set -euo pipefail

usage()
{
    echo "usage: qfix [-g] [<-s>|<--split>|<+s>|<--no-split>] [--help] [file...]"
}

ED_NAME="vim"
ED_OPTS=('--not-a-term' '-fX')
ED_ARGS=('+copen')
OTHER_OPTS=()

while [ $# -gt 0 ]
do
    case "$1" in
        --help)
            usage
            exit 0
            ;;
        +s|--no-split)
            ED_ARGS+=( '+set switchbuf-=split' )
            ;;
        -s|--split)
            ED_ARGS+=( '+set switchbuf+=split' )
            ;;
        -g)
            ED_NAME="vim"
            ED_OPTS=('--not-a-term' '-gfX')
            ;;
        -G)
            ED_NAME="vim"
            ED_OPTS=('--not-a-term' '-gX')
            ;;
        -*)
            usage
            exit 1
            ;;
         *)
            OTHER_OPTS+=("$1")
            ;;
    esac
    shift
done

EFILE=$(mktemp /tmp/qfix.XXXXXX)

trap "rm -f '$EFILE'" EXIT QUIT KILL TERM

if which paint 1>/dev/null 2>/dev/null
then
   ( cat "${OTHER_OPTS[@]+${OTHER_OPTS[@]}}" | tee "$EFILE" | paint )
else
   ( cat "${OTHER_OPTS[@]+${OTHER_OPTS[@]}}" | tee "$EFILE" )
fi

# Regular expression to find pattern ':<digits>:'
if grep -q -e "\:[[:digit:]]\+\:" $EFILE
then
    if [ $(cat "$EFILE" | sed -e "/^ *$/d" | wc -l) -gt 0 ]
    then
        ( exec </dev/tty; "${ED_NAME}" "${ED_OPTS[@]}" -q <(cat "$EFILE") "${ED_ARGS[@]}" )
        exit 1
    fi
fi

exit 0
