#!/bin/bash

set -euo pipefail

set_mouse() {
    local option=$1; shift;

    local value_old=$(tmux show-options -gwv mouse)

    if [[ $option == on ]]; then
        value_new=on
    elif [[ $option == off ]]; then
        value_new=off
    elif [[ $option == toggle && $value_old == on  ]]; then
        value_new=off
    elif [[ $option == toggle && $value_old == off ]]; then
        value_new=on
    elif [[ $option == print ]]; then
        tmux show-options -gwv mouse
        return 0
    else
        echo "invalid option: $option" 1>&2
        return 1
    fi

    if [[ $value_old != $value_new ]]; then
        tmux set-option -qg mouse "$value_new"
        tmux display-message "Mouse: $value_new"
        echo "$value_old -> $(tmux show-options -gwv mouse)"
    else
        tmux show-options -gwv mouse
    fi
}


if [ $# -gt 0 ]
then
    if [ "$1" == "-h" ]
    then
        shift;
        cat <<EOF
Usage: $0 [<on|off|toggle|print>]
       $0 -h

sets or resets the tmux mouse mode.

with no argument is specified, print is the default

options:
  -h    show this help
EOF
        exit 0;
    fi

    set_mouse "$1";
else
    set_mouse "print"
fi
