#! /usr/bin/perl

#http://unix.stackexchange.com/questions/4527/program-that-passes-stdin-to-stdout-with-color-codes-stripped

use strict;
use warnings;

while (<>) {
   s/\e\[?.*?[\@-~]//g; # Strip ANSI escape codes
   s/\e\[[\d;]*m//g;    # Strip ANSI color codes 
   print;
}
