#!/bin/bash

if [ $# -ne 1 ]
then
   echo "Usage: $(basename "$0") <screen-name-regex>" 1>&2
   exit 1;
fi

SCREEN_PID=$(screen -ls | grep -e "$1" | sed -e 's/^[[:space:]]*//' -e 's/[.].*//' | head -1);

ps -afe | grep -f <(sudo lsof -p "$SCREEN_PID" | grep -o 'pts/[0-9]*$' | sed -e 's/p/[[:space:]][p]/') | grep -e -bash | awk '{ print $2 }' | xargs -r echo run: kill -9
