#!/usr/bin/perl

use strict;

my $regexp   = $ARGV[0] || "^main";
my $qregexp1 = qr/$regexp/ . qr/[^{]*[{][ ]*$/;
my $qregexp2 = qr/$regexp/ . qr/[^{]*[ ]*$/;

my $matched       = 0;
my $bracket_level = 0;

my $full_line = "";

while ( my $line = <STDIN> )
{
   my $oldline;

   if ( $matched == 0 )
   {
      if ( $line =~ /$qregexp2/ )
      {
         while (1)
         {
            $oldline .= ( defined $oldline ? "\n" : "" ) . $line;

            last
              if ( !defined( $line = <STDIN> ) );

            next
              if ( $line =~ qr/^[ ]*$/ );

            $matched = 1
              if ( $line =~ qr/[{]/ );

            last;
         }
      }

      if ( $line =~ /$qregexp1/ )
      {
         $matched = 1
           if ( $matched == 0 && $bracket_level == 0 );
      }
   }

   if ( $matched == 1 )
   {
      if ( $line =~ /[{]/ )
      {
         ++$bracket_level
           if ( $matched == 1 );
      }

      if ( defined $line )
      {
         print $oldline
           if ( $matched == 1 && defined $oldline );

         print $line
           if ( $matched == 1 && $bracket_level > 0 );
      }

      if ( $line =~ /[}]/ )
      {
         --$bracket_level
           if ( $matched == 1 );

         $matched = 0
           if ( $bracket_level == 0 );
      }
   }
}
