#!/bin/bash
#
#   This file echoes a bunch of color codes to the 
#   terminal to demonstrate what's available.  Each 
#   line is the color code of one forground color,
#   out of 17 (default + 16 escapes), followed by a 
#   test use of that color on all nine background 
#   colors (default + 8 escapes).
#

if [ $# -lt 1 ]
then
   echo "Usage: $(basename "$0") <term|tmux>" 1>&2
   exit 1
fi

OPT="$1"

T='gYw'   # The test text

if [ "$OPT" == "term" ] || [ "$OPT" == "all" ]
then
   echo "TERM COLORS:"
   echo "-------------"

   echo "                 40m     41m     42m     43m     44m     45m     46m     47m";
   
      for FGs in '   0m' '   1m' '  30m' '1;30m' '  31m' '1;31m' '  32m' '1;32m' '  33m' '1;33m' '  34m' '1;34m' '  35m' '1;35m' '  36m' '1;36m' '  37m' '1;37m';
      do
         FG=${FGs// /}
         echo -en " $FGs \033[$FG  $T  "
         for BG in 40m 41m 42m 43m 44m 45m 46m 47m 26m;
            do echo -en "$EINS \033[$FG\033[$BG  $T  \033[0m";
         done
         echo
      done
   echo
fi

if [ "$OPT" == "tmux" ] || [ "$OPT" == "all" ]
then
   echo "TMUX COLORS:"
   echo "-------------"
   
   b=0
   for f in {0..255}
   do
      printf "[\x1b[48;5;%dm\x1b[38;5;%dm%s\x1b[0m] " "${b}" "${f}" "$(printf "%s%03d" "colour" "${f}")"

      if (( f % 8 == 7 ))
      then
         printf "\n";
      fi
   done

   echo "-------------"

   for b in {0..7}
   do
      for f in {0..7}
      do
         printf "[\x1b[48;5;%dm\x1b[38;5;%dm%s\x1b[0m] " "${b}" "${f}" "$(printf "%s%03d" "colour" "${f}")"

         if (( f % 8 == 7 ))
         then
            printf "\n";
         fi
      done
   done
fi
